//TODO: deprecated; use items.js instead; refactor me;
var dict = {
    "Change character": "Сменить персонажа",
    "Blacksmith": "Кузнец",
    "Tailor": "Портной",
    "Alchemyst": "Алхимик",
    "Farmer": "Фермер",
    "Carpenter": "Плотник",
    "Cook": "Повар",
    "Hunter": "Охотник",
    "Male": "Мужчина",
    "Female": "Женщина",
    "Enter": "Войти",
    "Apple tree log": "Яблоневое бревно",
    "Bulletin board": "Доска объявлений",
    "Bavarian sausage": "Баварская сосиска",
    "English breakfast": "Английский завтрак",
    "Intestines": "Кишки",
    "Coal powder": "Угольный порошок",
    "Activated carbon": "Активированный уголь",
    "Raw s pill": "Сырая С пилюля",
    "S pill": "С пилюля",
    "Raw v pill": "Сырая Ж пилюля",
    "V pill": "Ж пилюля",
    "Raw d pill": "Сырая Л пилюля",
    "D pill": "Л пилюля",
    "Raw i pill": "Сырая И пилюля",
    "I pill": "И пилюля",
    "Raw p pill": "Сырая В пилюля",
    "P pill": "В пилюля",
    "Raw w pill": "Сырая М пилюля",
    "W pill": "М пилюля",
    "Mushroom essence": "Грибная настойка",
    "Wall torch": "Настенный факел",
    "Ingot": "Слиток",
    "Meat grinder": "Мясорубка",
    "Minced meat": "Фарш",
    "Raw bread": "Сырой хлеб",
    "Bread": "Хлеб",
    "Bread slice": "Кусок хлеба",
    "Apple jam": "Яблочный джем",
    "Apple jam portion": "Порция яблочного джема",
    "Apple jam toast": "Тост с яблочным джемом",
    "Raw pizza": "Сырая пицца",
    "Pizza": "Пицца",
    "Saltwort": "Солянка",
    "Onion soup": "Луковый суп",
    "Pumpkin soup": "Тыквынный суп",
    "Vegetable soup": "Овощной суп",
    "Faction tribute": "Дань фракции",
    "Tour": "Экскурсия",
    "Drink water": "Выпить воды",
    "Interact": "Взаимодействовать",
    "Back": "Назад",
    "Buy sex": "Купить секс",
    "Buy": "Купить",
    "Take revenue": "Забрать выручку",
    "Take sold items": "Забрать выкупленные предметы",
    "Sell": "Продать",
    "Donate": "Поддержать проект",
    "Catch": "Поймать",
    "Release": "Отпустить",
    "Balance": "Баланс",
    "Tax": "Налог",
    "Next payment": "Следующий платеж",
    "Deposit": "Положить",
    "Withdraw" : "Снять",
    "Bank": "Банк",
    "Get claim": "Получить клейм",
    "Get village claim": "Получить деревенский клейм",
    "Quest": "Квест",
    "Set citizenship": "Установить гражданство",
    "Talk": "Говорить",
    "Select": "Выбрать",
    "Extend north": "Расширить на север",
    "Extend east": "Расширить на восток",
    "Extend south": "Расширить на юг",
    "Extend west": "Расширить на запад",
    "Shrink north": "Уменьшить на север",
    "Shrink east": "Уменьшить на восток",
    "Shrink south": "Уменьшить на юг",
    "Shrink west": "Уменьшить на запад",
    "Stake claim": "Клейм",
    "Starving": "Голод",
    "Thirsty": "Жажда",
    "Overeat": "Переедание",
    "Sitting": "Сидим",
    "Tool": "Инструмент",
    "Equipment": "Оборудование",
    "You must be near equipment": "Вы должны быть рядом с оборудованием",
    "Must be equipped": "Должен быть экипирован",
    "Skill is capped": "Навык ограничен",
    "Cap": "Предел",
    "Durability": "Прочность",
    "Value": "Значение",
    "Bung": "Пробка",
    "Flower essence": "Цветочная эссенция",
    "Anti plague potion": "Противочумное зелье",
    "Vial": "Флакон",
    "Requirements": "Требования",
    "Close": "Закрыть",
    "Help": "Справка",
    "Навыки [Skills]": "Навыки [Skills]",
    "Инвентарь": "Инвентарь",
    "Опыт": "Опыт",
    "Reset help": "Сбросить помощь",
    "Users": "Игроки",
    "Users online:": "Игроки онлайн:",
    "Map": "Карта",
    "Chat": "Чат",
    "System": "Система",
    "players": "игроки",
    "help": "справка",
    "Build": "Строить",
    "Bag": "Сумка",
    "Bed": "Кровать",
    "Bonfire": "Костер",
    "Brick wall": "Кирпичная стена",
    "Chest": "Сундук",
    "Millstone": "Жернов",
    "Oven": "Печь",
    "Wicker basket": "Плетеная корзина",
    "Wooden bed": "Деревянная кровать",
    "Wooden throne": "Деревянный трон",
    "Wooden armor": "Деревянный доспех",
    "Wooden helmet": "Деревянный шлем",
    "Wooden chair": "Деревянный стул",
    "Wooden table": "Деревянный стол",
    "Dining table": "Обеденный стол",
    "Wooden plate": "Деревянная тарелка",
    "Wooden shovel": "Деревянная лопата",
    "Wooden toilet": "Деревянный туалет",
    "Select recipe": "Выберите рецепт",
    "Craft": "Крафт",
    "Recipe": "Рецепт",
    "Bark": "Кора",
    "Bark mug": "Кружка из коры",
    "Bear rug": "Медвежья шкура",
    "Bone": "Кость",
    "Branch": "Ветка",
    "Bough": "Сук",
    "Stone": "Камень",
    "Trunk": "Ствол",
    "Log": "Бревно",
    "Board": "Доска",
    "Firewood": "Дрова",
    "Coal": "Уголь",
    "Charcoal": "Древесный уголь",
    "Ash": "Пепел",
    "Stick": "Палка",
    "Twig": "Прутик",
    "Grass": "Трава",
    "Skull": "Череп",
    "Bone saw": "Костяная пила",
    "Dildo": "Елдак",
    "Flask": "Фляжка",
    "Flour": "Мука",
    "Leather": "Кожа",
    "Leather helmet": "Кожаный шлем",
    "Leather armor": "Кожаная броня",
    "Leather leggings": "Кожаные поножи",
    "Leather boots": "Кожаные ботинки ",
    "Rogalik": "Рогалик",
    "Sharp stone": "Острый камень",
    "Soulstone": "Soulstone",
    "Steel helmet": "Стальной шлем",
    "Steel armor": "Стальная броня",
    "Steel leggings": "Стальные поножи",
    "Steel boots": "Стальные ботинки",
    "Steel plate": "Стальная пластина",
    "Steel ingot": "Слиток стали",
    "Iron helmet": "Железный шлем",
    "Iron armor": "Железная броня",
    "Iron leggings": "Железные поножи",
    "Iron boots": "Железные ботинки",
    "Stone axe": "Каменный топор",
    "Stone hammer": "Каменный молот",
    "Stone knife": "Каменный нож",
    "Steel sword": "Стальной меч",
    "Iron sword": "Железный меч",
    "Iron axe": "Железный топор",
    "Iron ingot": "Слиток железа",
    "Iron ore": "Железная руда",
    "Iron shovel": "Железная лопата",
    "Iron plate": "Железная пластина",
    "Wooden sword": "Деревянный меч",
    "Torch": "Факел",
    "Stats": "Статы",
    "Hp": "Жизнь",
    "Fullness": "Сытость",
    "Stamina": "Выносливость",
    "Strength": "Сила",
    "Intellect": "Интеллект",
    "Vitality": "Живучесть",
    "Dexterity": "Ловкость",
    "Charisma": "Харизма",
    "Luck": "Удача",
    "Protein": "Белки",
    "Carbohydrate": "Углеводы",
    "Fat": "Жиры",
    "Calcium": "Кальций",
    "Speed": "Скорость",
    "Armor": "Броня",
    "Defence": "Защита",
    "Accuracy": "Точность",
    "Exp": "Опыт",
    "Learning points": "Очки обучения",
    "Karma": "Карма",
    "Fame": "Слава",
    "Kills": "Убийства",
    "Players killed": "Убито игроков",
    "Death": "Смертей",
    "Equip": "Экипировка",
    "Settings": "Настройки",
    "Config": "Конфиг",
    "map": "map",
    "darkness": "darkness",
    "simpleDarkness": "simpleDarkness",
    "ray": "ray",
    "ui": "ui",
    "names": "names",
    "character": "character",
    "bald": "bald",
    "Debug": "Debug",
    "player": "игроки",
    "box": "box",
    "position": "position",
    "entity": "entity",
    "grid": "grid",
    "network": "network",
    "length": "length",
    "data": "data",
    "Skills": "Навыки",
    "Skill": "Навык",
    "Select skill to see it's description": "Выберите навык для просмотра его описания",
    "Learn": "Учить",
    "Logout": "Выйти",
    "Reset settings": "Сбросить настройки",
    "Blog": "Блог",
    "Bugtracker": "Багтрекер",
    "Group": "Группа",
    "Add": "Добавить",
    "Terra": "Земля",
    "thirsty": "жажда",
    "Fight": "Бой",
    "Space": "Пробел",
    "Punch": "Punch",
    "Kick": "Kick",
    "Head": "Голова",
    "Body": "Тело",
    "Feet": "Стопы",
    "Neck": "Шея",
    "Legs": "Ноги",
    "Right hand": "Правая рука",
    "Left hand": "Левая рука",
    "Block:": "Блок:",
    "Stoneworking": "Обработка камня",
    "Pottery": "Гончарное дело",
    "Lumberjacking": "Рубка леса",
    "Mining": "Горное дело",
    "Cooking": "Кулинария",
    "Farming": "Фермерство",
    "Leatherworking": "Обработка кожи",
    "Metalworking": "Обработка металла",
    "Mechanics": "Механика",
    "Swordsmanship": "Фехтование",
    "Tailoring": "Портняжное дело",
    "Carpentry": "Плотничество",
    "Survival": "Выживание",
    "Quality": "Качество",
    "Damage": "Урон",
    "Reload": "Перезагрузить",
    "Client error. Refresh page or try again later.": "Ошибка клиента. Обновите страницу или попробуйте позже.",
    "Refresh page...": "Обновите страницу...",
    "Login": "Логин",
    "Name": "Имя",
    "Password": "Пароль",
    "Repeat password": "Повторите пароль",
    "Create character": "Создать персонажа",
    "Sign up": "Зарегистрироваться",
    "Sign in": "Войти",
    "Drop": "Бросить",
    "Sac": "Мешочек",
    "Small sac": "Маленький мешочек",
    "Bone spear": "Костяное копье",
    "Rope": "Веревка",
    "Teeth trinket": "Ожерелье из зубов",
    "Clay": "Глина",
    "Clay brick bar": "Заготовка глиняного кирпича",
    "Clay cup": "Глиняная чашка",
    "Clay plate": "Глиняная тарелка",
    "Clay pot": "Глиняный горшок",
    "Plastic": "Пластик",
    "Plastic ore": "Пластиковая руда",
    "Stone pickaxe": "Каменная кирка",
    "Carrot": "Морковка",
    "Pumpkin": "Тыква",
    "Apple": "Яблоко",
    "Coconut": "Кокос",
    "Banana": "Банан",
    "Turnip": "Репа",
    "Raw carrot cake": "Сырой морковный торт",
    "Dough": "Тесто",
    "Chicken egg": "Куриное яйцо",
    "Wheat": "Пшеница",
    "Meat": "Мясо",
    "Rabbit meat": "Крольчатина",
    "Mushroom": "Гриб",
    "Fried chicken": "Жаренная курица",
    "Fried mushroom": "Жареный гриб",
    "Fried egg": "Яишница",
    "Rabbit roast": "Жаркое из кролика",
    "Chicken brisket": "Куриная грудка",
    "Chicken leg": "Куриная нога",
    "Chicken wing": "Куриное крыло",
    "Roasted chicken brisket": "Запеченная куриная грудка",
    "Roasted chicken leg": "Запеченная куриная нога",
    "Roasted chicken wing": "Запеченное куриное крыло",
    "Roasted meat": "Жареное мясо",
    "Robe": "Мантия",
    "High chance of failing": "Высокая вероятность неудачи",
    "Auto": "Авто",
    "Create": "Создать",
    "Raw hide": "Сырая шкура",
    "Dried hide": "Высушенная шкура",
    "Thread": "Нить",
    "Level": "Уровень",
    "novice": "начальный",
    "apprentice": "базовый",
    "expert": "экспертный",
    "master": "мастерский",
    "grandmaster": "грандмастерский",
    "Skill has it's maximum level": "Навык на максимальном уровне",
    "Unlocks {lvl} lvl of the {skill} skill": "Открывает {lvl} уровень навыка {skill}",
    "New maximum value": "Новое максимальное значение",
    "Cost": "Стоимость",
    "You have {amount} LP": "У вас есть {amount} очка(ов) обучения",
    "You need {diff} additional LP to learn this skill": "Вам нужно дополнительно {diff} очка(ов), чтобы выучить этот навык",
    "Drying frame": "Сушильная рама",
    "Respawn": "Респаун",
    "Roof": "Крыша",
    "Skull totem": "Тотем из черерпов",
    "Trap": "Ловушка",
    "Brick oven": "Кирпичная печь",
    "Clay vase": "Глиняная ваза",
    "Castle arc": "Булыжная арка",
    "Castle door": "Булыжная дверь",
    "Castle wall": "Булыжная стена",
    "Castle roof": "Булыжная крыша",
    "Castle floor": "Булыжный пол",
    "Forge": "Кузница",
    "Plastic chest": "Пластиковый сундук",
    "Plastic chair": "Пластиковый стул",
    "Plastic door": "Пластиковоя дверь",
    "Plastic floor": "Пластиковый пол",
    "Plastic roof": "Пластиковая крыша",
    "Plastic pillar": "Пластиковый столб",
    "Plastic smeltery": "Плавильня пластика",
    "Plastic table": "Пластиковый стол",
    "Plastic wall": "Пластиковая стена",
    "Russian oven": "Русская печь",
    "Stone tile": "Каменная кладка",
    "Well": "Колодец",
    "Bucket": "Ведро",
    "Sign": "Знак",
    "Tanning tub": "Дубильный таз",
    "Wooden chest": "Деревянный сундук",
    "Iron pipe": "Железная труба",
    "Wooden arc": "Деревянная арка",
    "Wooden door": "Деревянная дверь",
    "Wooden floor": "Деревянный пол",
    "Wooden pillar": "Деревянный столб",
    "Wooden wall": "Деревянная стена",
    "Wooden window": "Деревянное окно",
    "Wooden fence": "Деревянный забор",
    "Wooden fence connector": "Деревянный забор: соединитель",
    "Wooden fence cornerpost": "Деревянный забор: угол",
    "Wooden fence post": "Деревянный забор: столб",
    "Wooden gate": "Деревянные ворота",
    "Boulder": "Булыжник",
    "Stone block": "Каменная глыба",
    "Plastic block": "Пластиковая глыба",
    "Brick": "Кирпич",
    "Metal pipe": "Металлическая труба",
    "system": "сервер",
    "Disable help": "Отключить помощь",
    "Topics": "Темы",
    "Authors": "Авторы",
    "Straw": "Солома",
    "Water": "Вода",
    "Hammer": "Молот",
    "Grave": "Могила",
    "Book": "Книга",
    "Onion": "Лук репчатый",
    "Pick up": "Поднять",
    "Eat": "Съесть",
    "Fix": "Зафиксировать",
    "Destroy": "Разрушить",
    "Info": "Информация",
    "Grass plant": "Посаженная трава",
    "Harvest": "Собрать",
    "Fir tree plant": "Саженец ели",
    "Protein drug": "Препарат протеина",
    "Inject": "Ввести",
    "Iron chest": "Железный сундук",
    "Open": "Открыть",
    "Sort": "Сортировать",
    "Haystack": "Стог сена",
    "Copper gear": "Медный механизм",
    "Potato seed": "Семена картофеля",
    "Defecate": "Испражниться",
    "Pillow": "Подушка",
    "Anvil": "Наковальня",
    "Apple pie": "Яблочный пирог",
    "Roasted salmon": "Жареный лосось",
    "Meteorite leggings": "Метеоритная поножи",
    "Banana palm tree plant": "Саженец банановой пальмы",
    "Titanium knife": "Титановый нож",
    "Meteorite sword": "Метеоритный меч",
    "Salmon fillet": "Филе лосося",
    "Copper knife": "Медный нож",
    "Stick fence": "Веточное ограждение",
    "Black robe": "Черная мантия",
    "Christmas bauble": "Ёлочная игрушка",
    "Frying pan": "Сковорода",
    "Meteorite knife": "Метеоритный нож",
    "Meteorite pickaxe": "Метеоритная кирка",
    "Spinning wheel": "Прялка",
    "Lift": "Поднять",
    "Rotate": "Крутить",
    "O": "O",
    "Iron pickaxe": "Железная кирка",
    "Titanium pickaxe": "Титановая кирка",
    "Birch tree stub": "Пень березы",
    "Remove": "Убрать",
    "Sit": "Сесть",
    "Stand up": "Встать",
    "Banana palm tree stub": "Пень банановой пальмы",
    "Steel saw": "Стальная пила",
    "Dungeon entrance": "Вход в подземелье",
    "Meteorite axe": "Метеоритный топор",
    "Carrot seed": "Семена моркови",
    "Hemp seed": "Семена конопли",
    "Meteorite boots": "Метеоритные ботинки",
    "Wheat beer": "Пшеничное пиво",
    "Drink": "Пить",
    "Drink all": "Выпить все",
    "Cured meat": "Вяленое мясо",
    "Apple tree bark": "Кора яблони",
    "Christmas tree": "Новогодняя ёлка",
    "Chicken nest": "Гнездо курицы",
    "Sling": "Праща",
    "Apple tree stick": "Палка яблони",
    "Copper saw": "Медная пила",
    "Baked chicken leg": "Запеченная куриная нога",
    "Cupboard": "Шкаф",
    "Cave entrance": "Вход в пещеру",
    "Golden ore": "Золотая руда",
    "Titanium saw": "Татановая пила",
    "Vomit": "Рвота",
    "World picture": "Картина мира",
    "Plastic ingot": "Пластиковый слиток",
    "Sturgeon": "Осётр",
    "Gut": "Потрошить",
    "Rabbit corpse": "Труп кролика",
    "Roasted catfish": "Жареный сом",
    "Vendor license": "Торговая лицензия",
    "Pepper plant": "Саженец перца",
    "Lamp torch": "Светильник",
    "Meteorite ingot": "Метеоритный слиток",
    "Fabric bag": "Тканевая сумка",
    "Titanium helmet": "Титановый шлем",
    "Dragon leather": "Кожа дракона",
    "Roasted sturgeon": "Жареный осётр",
    "Farmer pants": "Фермерские штаны",
    "Straw roof": "Соломенная крыша",
    "Fat drug": "Жировой препарат",
    "Loom": "Ткацкий станок",
    "Furnace": "Горн",
    "Burn": "Поджечь",
    "Pepper seed": "Семена перца",
    "Empty": "Опустошить",
    "Fill": "Заполнить",
    "Snowball": "Снежок",
    "Tobacco plant": "Саженец табака",
    "Stone gate": "Каменные ворота",
    "Lock": "Закрыть",
    "Unlock": "Открыть",
    "Wheat malt": "Пшеничный солод",
    "Potato plant": "Саженец картофеля",
    "Wine bottle": "Винная бутылка",
    "Pricelist": "Цены",
    "K": "K",
    "Silver ore": "Серебряная руда",
    "Shuffle": "Перемешать",
    "Copper pickaxe": "Медная кирка",
    "Fir tree stub": "Пень ели",
    "Iron saw": "Железная пила",
    "Hop seed": "Семена хмеля",
    "Portion of awesome rabbit": "Порция охрененного кролика",
    "Roasted perch": "Жареный окунь",
    "Carrot cake": "Морковный торт",
    "Titanium sword": "Титановый меч",
    "Farmer hat": "Фермерская шляпа",
    "Soil": "Почва",
    "Rinse": "Прополаскать",
    "Apple tree bough": "Сук яблони",
    "Break off": "Сломать",
    "Beer bottle": "Бутылка под пиво",
    "Steel hammer": "Стальной молот",
    "Quiver": "Колчан",
    "Worm": "Червь",
    "Garbage": "Мусор",
    "Hemp cake": "Конопляный кекс",
    "Catfish fillet": "Филе сома",
    "Silver ingot": "Серебряный слиток",
    "Shield and axes": "Щит и топоры",
    "Sturgeon fillet": "Филе осётра",
    "Titanium boots": "Титановые ботинки",
    "Crystal": "Кристалл",
    "Stick gate": "Веточные ворота",
    "Farmer boots": "Фермерские ботинки",
    "Steel pickaxe": "Стальная кирка",
    "Boulder wall": "Стена из волунов",
    "Make window": "Сделать окно",
    "Banana palm tree": "Банановая пальма",
    "Chop": "Рубить",
    "Get bark": "Содрать кору",
    "Get bough": "Сорвать сук",
    "Get branch": "Сорвать ветку",
    "Get seed": "Получить семена",
    "Get banana": "Сорвать банан",
    "G": "G",
    "Perch": "Окунь",
    "Stone tower": "Каменный столб",
    "Onion seed": "Семена лука",
    "Copper axe": "Медный топор",
    "Present": "Подарок",
    "Unpack": "Распаковать",
    "Glass tube": "Стеклянная труба",
    "Flax fiber": "Волокна льна",
    "Injector": "Шприц",
    "Titanium ingot": "Титановый слиток",
    "R": "R",
    "Copper shovel": "Медная лопата",
    "Meteorite saw": "Метеоритная пила",
    "I": "I",
    "Banana palm tree bark": "Кора банановой пальмы",
    "Bookshelf": "Книжный шкаф",
    "Sand": "Песок",
    "Chicken carcass": "Тушка курицы",
    "Cut": "Разрезать",
    "Raw apple pie": "Сырой яблочный пирог",
    "Portal": "Портал",
    "Edit": "изменить",
    "Read": "прочитать",
    "Rogalik small banner": "Маленькое знамя Рогалика",
    "Palm tree trunk": "Ствол пальмы",
    "Corpse": "Тело",
    "man-corpse": "Человеческое тело",
    "Meteorite armor": "Метеоритная броня",
    "Palm tree bark": "Кора пальмы",
    "Fried vegetables": "Жареные овощи",
    "Joint": "Косяк",
    "Smoke": "Курить",
    "Wine": "Вино",
    "Platinum ingot": "Платиновый слиток",
    "Pike fillet": "Филе щуки",
    "Turnip seed": "Семена репы",
    "Energy gun": "Энергетическая пушка",
    "Cigarette": "Сигарета",
    "Iron fence pillar": "Столб железного забора",
    "Caravan": "Фургон",
    "Grape plant": "Саженец винограда",
    "Flax yarn": "Льняная пряжа",
    "Bone chest": "Костяной сундук",
    "Small atomic container": "Малый атомный контейнер",
    "Stone wall": "Каменная стена",
    "Roasted mutton": "Жареная баранина",
    "Yellow snowball": "Желтый снежок",
    "Stone column": "Каменная колонна",
    "Flower": "Цветок",
    "Birch tree": "Берёза",
    "Baked chicken brisket": "Запеченная куриная грудинка",
    "Paper": "Бумага",
    "Flax plant": "Саженец льна",
    "Turnip plant": "Саженец репы",
    "Shield and swords": "Щит и мечи",
    "Castle cellar exit": "Выход из подземелья замка",
    "Bone dice": "Костяные кости",
    "Roll": "Бросить",
    "Roll five": "Бросить пять",
    "Carassius": "Карась",
    "Pumpkin plant": "Саженец тыквы",
    "Fir tree seed": "Семена ели",
    "Wooden shield": "Деревянный щит",
    "Stone door": "Каменная дверь",
    "Stone dice": "Каменные кости",
    "Circle of fire": "Круг огня",
    "Meteorite ore": "Метеоритная руда",
    "Disassemble": "Разобрать",
    "Onion plant": "Саженец лука",
    "Pumpkin seed": "Семена тыквы",
    "Clay brick": "Глиняный кирпич",
    "Copper ore": "Медная руда",
    "Silver": "Серебро",
    "L": "L",
    "Grape": "Виноград",
    "Apple tree trunk": "Ствол яблони",
    "Carrot plant": "Саженец моркови",
    "Banana palm tree trunk": "Ствол банановой пальмы",
    "Copper ingot": "Медный слиток",
    "Stone arc": "Каменная арка",
    "Green onion": "Зеленый лук",
    "Carassius fillet": "Филе карася",
    "Rogalik banner": "Знамя Рогалика",
    "Salmon": "Лосось",
    "Titanium leggings": "Титановая поножи",
    "Fir tree twig": "Прутик ели",
    "Meteorite plate": "Метеоритная пластина",
    "head": "Голова",
    "Skin": "Кожа",
    "Flax": "Лён",
    "Birch tree plant": "Саженец березы",
    "Meteorite shovel": "Метеоритная лопата",
    "Raw hemp cake": "Сырой конопляный кекс",
    "Birch tree trunk": "Ствол березы",
    "Meteorite hammer": "Метеоритный молот",
    "Crossbow": "Арбалет",
    "Minor healing potion": "Малое зелье лечения",
    "Chicken feather": "Куриное перо",
    "Mutton pie": "Пирог из баранины",
    "Iron knife": "Желеный нож",
    "Mythril ore": "Митриловая руда",
    "Apple tree": "Яблоня",
    "Get apple": "Сорвать яблоко",
    "Cured tobacco leaf": "Высушенный табачный лист",
    "Glass": "Стекло",
    "Roasted carassius": "Жареный карась",
    "Wattle fence": "Плетёный забор",
    "Energy": "Энергия",
    "Palm tree stub": "Пень пальмы",
    "Wheat plant": "Саженец пшеницы",
    "Perch fillet": "Филе окуня",
    "Gold": "Золото",
    "Tobacco seed": "Семена табака",
    "Hemp plant": "Саженец конопли",
    "Torii": "Тории",
    "Arena": "Арена",
    "Transmutation circle": "Круг превращения",
    "Pepper": "Перец",
    "Platinum ore": "Платиновая руда",
    "Coin": "Монета",
    "Respown": "Респоун",
    "Set respawn": "Назначить место возрождения",
    "Teleport": "Телепортироваться",
    "Hop": "Хмель",
    "Castle cellar entrance": "Вход в подземелье замка",
    "Titanium hammer": "Титановый молот",
    "Linen": "Полотно льна",
    "Shit": "Дерьмо",
    "Bream": "Лещ",
    "Iron fence": "Желеный забор",
    "Iron wicket gate": "Железные ворота",
    "Fir tree bough": "Сук ели",
    "Birch tree branch": "Ветка березы",
    "Farmer shirt": "Фермерская рубашка",
    "Copper hammer": "Медный молот",
    "Iron shield": "Железный щит",
    "Meteorite helmet": "Метеоритный шлем",
    "Bark basket": "Корзина из коры",
    "A": "A",
    "Small atomic trap": "Малая атомная ловушка",
    "Stone pillar": "Каменный столб",
    "Potato": "Картофель",
    "Apple tree seed": "Семена яблони",
    "Hemp": "Конопля",
    "Meat pie": "Мясной пирог",
    "Bunch of cured meat": "Гроздь вяленого мяса",
    "Slice": "Разрезать",
    "Fir tree trunk": "Ствол ели",
    "Flax seed": "Семена льна",
    "Straw basket": "Соломенная корзина",
    "Apple tree twig": "Прутик яблони",
    "Iron hammer": "Железный молот",
    "Cave exit": "Выход из пещеры",
    "Ufo": "НЛО",
    "Awesome rabbit with vegetables": "Охрененный кролик с овощами",
    "Landscape picture": "Изображение пейзажа",
    "Birch tree bark": "Березовая кора",
    "Platinum": "Платина",
    "Carbohydrate drug": "Препарат Углеводов",
    "Stone stairs exit": "Выход по каменной лестнице",
    "Fir tree": "Ель",
    "Iron chamber pot": "Железный ночной горшок",
    "Iron scythe": "Железная коса",
    "chicken-corpse": "Труп курицы",
    "Small transmutation circle": "Малый круг превращения",
    "Baked meat": "Запеченное мясо",
    "Roasted pike": "Жареная щука",
    "Grape seed": "Семена винограда",
    "Pike": "Щука",
    "Apple tree plant": "Саженец яблони",
    "Orange": "Апельсин",
    "Mythril ingot": "Митриловый слиток",
    "Bream fillet": "Филе леща",
    "Catfish": "Сом",
    "Altar": "Алтарь",
    "Bugreport": "Сообщить об ошибке",
    "Steel knife": "Стальной нож",
    "Swordsman statue": "Статуя мечника",
    "Palm tree seed": "Семена пальмы",
    "Palm tree plant": "Саженец пальмы",
    "Titanium ore": "Титановая руда",
    "Vendor post": "Торговая точка",
    "Brick floor": "Кирпичный пол",
    "Apple tree branch": "Ветка яблони",
    "Sword and axe": "Меч и топор",
    "Brick door": "Кирпичная дверь",
    "Arrow": "Стрела",
    "Turnip slice": "Кусок репы",
    "Hop plant": "Саженец хмеля",
    "Weed": "Конопля",
    "Dragon ass skin bag": "Сумка из кожи с жопы дракона",
    "Birch tree seed": "Семена березы",
    "Tobacco": "Табак",
    "Cirno picture": "Изображение Сырно",
    "Copper pipe": "Медная труба",
    "Steel axe": "Стальной меч",
    "Birch tree stick": "Палка березы",
    "Mutton": "Баранина",
    "Baked chicken wing": "Запеченная куриное крыло",
    "Wooden bow": "Деревянный лук",
    "Waypoint": "Точка телепортации",
    "Titanium plate": "Титановая пластина",
    "Fir tree stick": "Палка Ели",
    "Butterfly wings": "Крылья бабочки",
    "Whitebait": "Малёк",
    "Wheat seed": "Семена пшеницы",
    "Apple tree stub": "Пень яблони",
    "Roasted bream": "Жареный лещ",
    "Scimitar": "Ятаган",
    "Titanium shovel": "Титановая лопата",
    "Fir tree branch": "Ветка ели",
    "Birch tree bough": "Сук березы",
    "Small swordsman statue": "Малая статуя мечника",
    "Raw meat pie": "Сырой мясной пирог",
    "Cigar": "Сигара",
    "Wooden plow": "Деревянный плуг",
    "Plow": "Пахать",
    "Stop": "Остановить",
    "Tobacco leaf": "Табачный лист",
    "Peach": "Персик",
    "Firesword": "Огненный меч",
    "Rude fishing rod": "Грубая удочка",
    "Dungeon exit": "Выход из подземелья",
    "Palm tree": "Пальма",
    "Get coconut": "Сорвать кокос",
    "Pumpkin slice": "Кусок тыквы",
    "Birch tree twig": "Прутик березы",
    "Titanium axe": "Титановый топор",
    "Calcium drug": "Препарат кальция",
    "Shashlik": "Шашлык",
    "Stone stairs entrance": "Вход по каменной лестнице",
    "Herbalist table": "Стол травника",
    "Golden ingot": "Золотой слиток",
    "Golden rogalik banner": "Золотое знамя Рогалика",
    "Baked potato": "Запеченный картофель",
    "Raw mutton pie": "Сырой пирог из баранины",
    "Stack of wood": "Поленница",
    "Titanium armor": "Титановая броня",
    "Fir tree bark": "Кора ели",
    "Banana palm tree seed": "Семена банановой пальмы",
    "Copper bath": "Медная ванна",
    "Barrel": "Бочка",
    "Alchemy": "Алхимия",
    "Herbalism": "Травничество",
    "Fishing": "Рыболовство",
    "Leadership": "Лидерство",
    "Perception": "Восприятие",
    "Phosphorus": "Фосфор",
    "Magnesium": "Магний",
    "Status points": "Статусные очки",
    "Wisdom": "Мудрость",
    "Move all": "Переместить всё",
    "News": "Новости",
    "Forum": "Форум",
    "Craft all": "Сдел. всё",
    "Knife": "Нож",
    "portable": "ручное",
    "liftable": "перетаскиваемое",
    "static": "статичное",
    "unavailable": "недоступное",
    "Chip": "Отколоть",
    "Sleep": "Спать",
    "Wake up": "Проснуться",
    "Saw": "Пила",
    "Split": "Раздробить",
    "rabbit-corpse": "Труп кролика",
    "Plunder": "Разграбить",

    "Access denied": "Доступ запрещен",
    "Already buying": "Уже покупается",
    "Already in container": "Уже в контейнере",
    "Already plowing": "Уже пашется",
    "Amount must be greater then zero": "Величина должна быть больше нуля",
    "Bad luck. Try again :3": "Неудача. Попробуйте ещё раз :3",
    "Bonfire must be burning": "Костёр должен гореть",
    "Cannot build there": "Нельзя построить здесь",
    "Cannot buy that": "Нельзя купить это",
    "Cannot chop (no space for trunk)" : "Невозможно срубить (нет места под ствол)",
    "Cannot destroy non empty item": "Нельзя уничтожить непустой предмет",
    "Cannot destroy your bag": "Нельзя уничтожить вашу сумку",
    "Cannot dig there": "Нельзя копать здесь",
    "Cannot disassemble non-crafted item": "Нельзя разобрать нерукотворный предмет",
    "Cannot drop there": "Нельзя бросить сюда",
    "Cannot edit": "Нельзя редактировать",
    "Cannot fill with that": "Нельзя наполнить этим",
    "Cannot insert this item into container": "Нельзя поместить этот предмет в контейнер",
    "Cannot insert this item into that container": "Нельзя поместить этот предмет в этот контейнер",
    "Cannot mount": "Нельзя оседлать",
    "Cannot pick up entity: not found": "Нельзя поднять вещь: не найдена",
    "Cannot place big container in small one": "Нельзя поместить большие контейнеры в маленькие",
    "Cannot place item into itself": "Нельзя поместить предмет в себя",
    "Cannot plant there": "Нельзя посадить здесь",
    "Cannot ride while plowing": "Нельзя оседлать когда пашешь",
    "Cannot rotate: collision": "Невозможно повернуть: преграда",
    "Cannot sell that": "Нельзя продать это",
    "Cannot split: amount is to big": "Нельзя раздробить: величина слишком большая",
    "Cannot swamp here": "Невозможно осушить это место",
    "Cannot tan that": "Невозможно это дубить",
    "Cannot teleport: out of map": "Невозможно переместиться: вне пределах карты",
    "Cannot use that as fuel": "Нельзя использовать это в качестве топлива",
    "Captcha is invalid": "Капча некорректна",
    "Chat message cannot be empty": "Сообщение не может быть пустым",
    "Chat message is to big": "Сообщение слишком большое",
    "Clean up before drink": "Почистите перед тем как пить",
    "Clean up before fill": "Почистите перед наполнением",
    "Clean up before use": "Почистите перед использованием",
    "Container is full": "Контейнер полон",
    "Enemy is offline": "Враг не в игре",
    "Exit portal not found": "Выход через портал не найден",
    "Fill with water before use": "Наполните водой перед использованием",
    "Fuel is full": "Уже заполнено топливом",
    "It cannot be disassembled": "Нельзя разобрать",
    "It's busy!": "Это занято!",
    "It's busy": "Это занято",
    "It's dead": "Оно мертво",
    "It's not your respawn": "Это не ваша точка возрождения",
    "It's too small": "Это слишком мало",
    "I want some atoms!": "Я хочу немного атомов!",
    "Login already exists": "Имя уже занято",
    "Login cannot be empty": "Поле имени должно быть заполнено",
    "Lot not found": "Лот не найден",
    "Must be built on the soil": "Может быть построено только на земле",
    "Name must start with letter and can contain only letters or digits": "Имя должно начинаться с буквы и содержать только буквы и цифры",
    "No fuel": "Нет топлива",
    "No revenue": "Нет дохода",
    "Not enough ingredients": "Недостаточно ингредиентов",
    "Nothing sold": "Ничего не было продано",
    "Nothing to harvest": "Нет ничего, что можно было бы собрать",
    "Password cannot be empty": "Поле пароля должно быть заполнено",
    "Seed can be planted only on the plowed soil": "Семена могут быть посажены только в пропаханную землю",
    "Server too busy. Please try again later": "Сервер занят. Попробуйте позже",
    "She is busy": "Она занята",
    "Sorry, registration is disabled": "Извините, регистрация закрыта",
    "Target is already dead": "Цель уже мертва",
    "The leather is not ready yet": "Кожа ещё не готова",
    "There is no free space in your bag": "Нет больше свободного места в вашей сумке",
    "This portal is not working": "Портал не работает",
    "This tree has no ": "Это дерево не имеет",
    "This tree has no bark": "Это дерево не имеет коры",
    "This tree has no boughs": "Это дерево не имеет сучьев",
    "This tree has no branches": "Это дерево не имеет веток",
    "This tree has no seed": "Это дерево не имеет семян",
    "This wall cannot has window": "Эта стена не может иметь окон",
    "Vendor is dead": "Торговец мертв",
    "Wrong channel or command": "Неправильный канал или команда",
    "wrong params": "Неправильные параметры",
    "Wrong password": "Неправильный пароль",
    "You are already lifting": "Вы уже что-то тащите",
    "You are banned": "Вы забанены",
    "You are disabled": "Ваши возможности были ограничены",
    "You are not a citizen": "Вы не гражданин",
    "You are not allowed to do this": "Вам непозволено делать это",
    "You are too weak": "Вы слишком слабы",
    "You cannot craft from that": "Вы не можете изготавливать из этого",
    "You cannot dig when you are tired": "Вы не можете копать когда устали",
    "You cannot disassemble it": "Вы не можете разобрать это",
    "You cannot do that": "Вы не можете это делать",
    "You cannot drop that": "Вы не можете бросить это",
    "You cannot fish there": "Вы не можете рыбачить здесь",
    "You cannot lift that": "Вы не можете поднять это",
    "You cannot lift when you are tired": "Вы не можете поднимать тяжести когда устали",
    "You cannot lock this gate": "Вы не можете запереть эту дверь",
    "You cannot move that": "Вы не можете передвинуть это",
    "You cannot plow when you are tired": "Вы не можете пахать когда вы устали",
    "You cannot sell that": "Вы не можете продать это",
    "You cannot unlock this gate": "Вы не можете отпереть эту дверь",
    "You cannot use that": "Вы не можете использовать это",
    "You do not have enough money": "У вас недостаточно денег",
    "You failed to mine here": "Попытка добычи провалилась",
    "You have no ammo": "У вас нет боезапаса",
    "You have no bag": "У вас нет сумки",
    "You have no permission to destroy that": "У вас нет полномочий это уничтожать",
    "You must be near transmutation circle to disassemble": "Вы должны быть возле круга превращения чтобы разбирать что-то",
    "You need a bait": "Вам нужна наживка",
    "You need a farming skill to plant seeds": "Вам нужен опыт в фермерстве чтобы сажать семена",
    "You need an alchemy skill to disassemble": "Вам нужен опыт в алхимии для разбора вещи",
    "You need a ranged weapon to shot": "Вам нужно оружие дальнего боя чтобы стрелять",
    "You need a shovel to destroy stub": "Вам нужна лопата чтобы выкорчевать пень",
    "You need a vessel of water": "Вам нужен сосуд для воды",
    "Your target is dead": "Ваша цель мертва",
    "You've finished this quest today": "Вы уже выполнили этот квест сегодня",
    "Zero quantity is not allowed": "Нулевая величина запрещена",
    "Drop ingredients here": "Перетащите ингредиенты сюда",

    "horse": "Лошадь",
    "rabbit": "Кролик",
    "dog": "Собака",
    "cat": "Кошка",
    "wolf": "Волк",
    "cow": "Корова",
    "pony": "Пони",
    "chicken": "Курица",
    "butterfly": "Бабочка",
    "sheep": "Овца",
    "kitty": "Кот-Разбойник",
    "Use": "Использовать",
};
