var dict = {
    "Requirements": "Требования",
    "Close": "Закрыть",
    "Help": "Справка",
    "Навыки [Skills]": "Навыки [Skills]",
    "Инвентарь": "Инвентарь",
    "Опыт": "Опыт",
    "Reset help": "Сбросить помощь",
    "Users": "Игроки",
    "Users online:": "Игроки онлайн:",
    "Map": "Карта",
    "Chat": "Чат",
    "System": "Система",
    "players": "игроки",
    "help": "справка",
    "Build": "Строить",
    "Bag": "Сумка",
    "Bed": "Кровать",
    "Bonfire": "Костер",
    "Brick wall": "Каменная стена",
    "Chest": "Сундук",
    "Millstone": "Жернов",
    "Oven": "Печь",
    "Wicker basket": "Плетеная корзина",
    "Wooden bed": "Деревянная кровать",
    "Wooden chair": "Деревянный стул",
    "Wooden table": "Деревянный стол",
    "Wooden plate": "Деревянная тарелка",
    "Wooden shovel": "Деревянная лопата",
    "Select recipe": "Выберите рецепт",
    "Craft": "Крафт",
    "Bark": "Кора",
    "Bark mug": "Кружка из коры",
    "Bear rug": "Медвежья шкура",
    "Bone": "Кость",
    "Branch": "Ветка",
    "Bough": "Сук",
    "Stone": "Камень",
    "Trunk": "Ствол",
    "Log": "Бревно",
    "Board": "Доска",
    "Firewood": "Дрова",
    "Coal": "Уголь",
    "Charcoal": "Древесный уголь",
    "Ash": "Пепел",
    "Stick": "Палка",
    "Twig": "Прутик",
    "Grass": "Трава",
    "Skull": "Череп",
    "Bone saw": "Костяная пила",
    "Dildo": "Елдак",
    "Flask": "Фляжка",
    "Flour": "Мука",
    "Leather": "Кожа",
    "Leather helmet": "Кожаный шлем",
    "Leather armor": "Кожаная броня",
    "Leather leggings": "Кожаные поножи",
    "Leather boots": "Кожаные ботинки ",
    "Rogalik": "Рогалик",
    "Sharp stone": "Острый камень",
    "Soulstone": "Soulstone",
    "Steel helmet": "Стальной шлем",
    "Steel armor": "Стальная броня",
    "Steel leggings": "Стальные поножи",
    "Steel boots": "Стальные ботинки",
    "Steel plate": "Стальная пластина",
    "Steel ingot": "Слиток стали",
    "Iron helmet": "Железный шлем",
    "Iron armor": "Железная броня",
    "Iron leggings": "Железные поножи",
    "Iron boots": "Железные ботинки",
    "Stone axe": "Каменный топор",
    "Stone hammer": "Каменный молот",
    "Stone knife": "Каменный нож",
    "Steel sword": "Стальной меч",
    "Iron sword": "Железный меч",
    "Iron axe": "Железный топор",
    "Iron ingot": "Слиток железа",
    "Iron ore": "Железная руда",
    "Iron shovel": "Железная лопата",
    "Iron plate": "Железная пластина",
    "Wooden sword": "Деревянный меч",
    "Torch": "Факел",
    "Stats": "Статы",
    "Hp": "Жизнь",
    "Fullness": "Сытость",
    "Stamina": "Выносливость",
    "Strength": "Сила",
    "Intellect": "Интеллект",
    "Vitality": "Живучесть",
    "Dexterity": "Ловкость",
    "Charisma": "Харизма",
    "Luck": "Удача",
    "Protein": "Белки",
    "Carbohydrate": "Углеводы",
    "Fat": "Жиры",
    "Calcium": "Кальций",
    "Speed": "Скорость",
    "Armor": "Броня",
    "Defence": "Защита",
    "Accuracy": "Точность",
    "Exp": "Опыт",
    "Learning points": "Очки обучения",
    "Karma": "Карма",
    "Fame": "Слава",
    "Kills": "Убийства",
    "Players killed": "Убито игроков",
    "Death": "Смертей",
    "Equip": "Экипировка",
    "Settings": "Настройки",
    "Config": "Конфиг",
    "map": "map",
    "darkness": "darkness",
    "simpleDarkness": "simpleDarkness",
    "ray": "ray",
    "ui": "ui",
    "names": "names",
    "character": "character",
    "bald": "bald",
    "Debug": "Debug",
    "player": "player",
    "box": "box",
    "position": "position",
    "entity": "entity",
    "grid": "grid",
    "network": "network",
    "length": "length",
    "data": "data",
    "Skills": "Навыки",
    "Skill": "Навык",
    "Select skill to see it's description": "Выберите навык для просмотра его описания",
    "Learn": "Учить",
    "Logout": "Выйти",
    "Reset interface": "Сбросить интерфейс",
    "Blog": "Блог",
    "Bugtracker": "Багтрекер",
    "Group": "Группа",
    "Add": "Добавить",
    "Terra": "Земля",
    "thirsty": "жажда",
    "Fight": "Бой",
    "Space": "Пробел",
    "Punch": "Punch",
    "Kick": "Kick",
    "Head": "Голова",
    "Body": "Тело",
    "Feet": "Стопы",
    "Neck": "Шея",
    "Legs": "Ноги",
    "Right hand": "Правая рука",
    "Left hand": "Левая рука",
    "Block:": "Блок:",
    "Stoneworking": "Обработка камня",
    "Pottery": "Гончарное дело",
    "Lumberjacking": "Рубка леса",
    "Mining": "Горное дело",
    "Cooking": "Кулинария",
    "Farming": "Фермерство",
    "Leatherworking": "Обработка кожи",
    "Metalworking": "Обработка металла",
    "Mechanics": "Механика",
    "Swordsmanship": "Фехтование",
    "Tailoring": "Портняжное дело",
    "Carpentry": "Плотничество",
    "Survival": "Выживание",
    "Quality": "Качество",
    "Damage": "Урон",
    "Reload": "Перезагрузить",
    "Client error. Refresh page or try again later.": "Ошибка клиента. Обновите страницу или попробуйте позже.",
    "Refresh page...": "Обновите страницу...",
    "Login": "Логин",
    "Name": "Имя",
    "Password": "Пароль",
    "Repeat password": "Повторите пароль",
    "Create character": "Создать персонажа",
    "Sign up": "Зарегистрироваться",
    "Sign in": "Войти",
    "Drop": "Бросить",
    "Sac": "Мешочек",
    "Small sac": "Маленький мешочек",
    "Bone spear": "Костяное копье",
    "Rope": "Веревка",
    "Teeth trinket": "Ожерелье из зубов",
    "Clay": "Глина",
    "Clay brick bar": "Заготовка глиняного кирпича",
    "Clay cup": "Глиняная чашка",
    "Clay plate": "Глиняная тарелка",
    "Clay pot": "Глиняный горшок",
    "Plastic": "Пластик",
    "Plastic ore": "Пластиковая руда",
    "Stone pickaxe": "Каменная кирка",
    "Carrot": "Морковка",
    "Pumpkin": "Тыква",
    "Apple": "Яблоко",
    "Coconut": "Кокос",
    "Banana": "Банан",
    "Turnip": "Репа",
    "Raw carrot cake": "Сырой морковный торт",
    "Dough": "Тесто",
    "Chicken egg": "Куриное яйцо",
    "Wheat": "Пшеница",
    "Meat": "Мясо",
    "Rabbit meat": "Крольчатина",
    "Mushroom": "Гриб",
    "Fried chicken": "Жаренная курица",
    "Fried mushroom": "Жареный гриб",
    "Fried egg": "Яишница",
    "Rabbit roast": "Жаркое из кролика",
    "Chicken brisket": "Куриная грудка",
    "Chicken leg": "Куриная нога",
    "Chicken wing": "Куриное крыло",
    "Roasted chicken brisket": "Запеченная куриная грудка",
    "Roasted chicken leg": "Запеченная куриная нога",
    "Roasted chicken wing": "Запеченное куриное крыло",
    "Roasted meat": "Жареное мясо",
    "Robe": "Мантия",
    "High chance of failing": "Высокая вероятность неудачи",
    "Auto": "Авто",
    "Create": "Создать",
    "Raw hide": "Сырая шкура",
    "Dried hide": "Высушенная шкура",
    "Thread": "Нить",
    "Level": "Уровень",
    "novice": "начальный",
    "apprentice": "базовый",
    "expert": "экспертный",
    "master": "мастерский",
    "grandmaster": "грандмастерский",
    "Skill has it's maximum level": "Навык на максимальном уровне",
    "Unlocks {lvl} lvl of the {skill} skill": "Открывает {lvl} уровень навыка {skill}",
    "New maximum value": "Новое максимальное значение",
    "Cost": "Стоимость",
    "You have {amount} LP": "У вас есть {amount} очков обучения",
    "You need {diff} additional LP to learn this skill": "Вам нужно дополнительно {diff} очка(ов), чтобы выучить этот навык",
    "Drying frame": "Сушильная рама",
    "Respawn": "Респаун",
    "Roof": "Крыша",
    "Skull totem": "Тотем из черерпов",
    "Trap": "Ловушка",
    "Brick oven": "Кирпичная печь",
    "Clay vase": "Глиняная ваза",
    "Castle arc": "Булыжная арка",
    "Castle door": "Булыжная дверь",
    "Castle wall": "Булыжная стена",
    "Castle roof": "Булыжная крыша",
    "Castle floor": "Булыжный пол",
    "Forge": "Кузница",
    "Plastic chest": "Пластиковый сундук",
    "Plastic chair": "Пластиковый стул",
    "Plastic door": "Пластиковоя дверь",
    "Plastic floor": "Пластиковый пол",
    "Plastic roof": "Пластиковая крыша",
    "Plastic pillar": "Пластиковый столб",
    "Plastic smeltery": "Плавильня пластика",
    "Plastic table": "Пластиковый стол",
    "Plastic wall": "Пластиковая стена",
    "Russian oven": "Русская печь",
    "Stone tile": "Каменная кладка",
    "Well": "Колодец",
    "Bucket": "Ведро",
    "Sign": "Знак",
    "Tanning tub": "Дубильный таз",
    "Wooden chest": "Деревянный сундук",
    "Iron pipe": "Железная труба",
    "Wooden arc": "Деревянная арка",
    "Wooden door": "Деревянная дверь",
    "Wooden floor": "Деревянный пол",
    "Wooden pillar": "Деревянный столб",
    "Wooden wall": "Деревянная стена",
    "Wooden window": "Деревянное окно",
    "Wooden fence": "Деревянный забор",
    "Wooden fence connector": "Деревянный забор: соединитель",
    "Wooden fence cornerpost": "Деревянный забор: угол",
    "Wooden fence post": "Деревянный забор: столб",
    "Wooden gate": "Деревянные ворота",
    "Boulder": "Булыжник",
    "Stone block": "Каменная глыба",
    "Plastic block": "Пластиковая глыба",
    "Brick": "Кирпич",
    "Metal pipe": "Металлическая труба",
    "system": "сервер",
    "player": "игроки",
    "Disable help": "Отключить помощь",
    "Topics": "Темы",
    "Users online:": "Игроки онлайн:",
    "Authors": "Авторы",
    "Straw": "Солома",
    "Water": "Вода",
    "Hammer": "Молот",
    "Grave": "Могила",
    "Book": "Книга",
}
